apiVersion: v1
kind: BuildConfig
metadata:
  name: "chronograf"
  labels:
    app: "cicd-chronograf"
    version: "1.7"
  annotations:
    description: "Builds the MongoDB ebis container."
    template.alpha.openshift.io/wait-for-ready: "true"
spec:
  source:
    git:
      uri: "https://github.com/DarrenMun/TestDocker/blob/master"
    sourceSecret:
      name: ignore-https-gitconf
    contextDir: chronograf.dockerfile
  strategy:
    dockerStrategy:
      buildargs:
      - name: NEXUS_ARTIFACT_URL
        value: "https://nexus-continuousintegration-dev.app.dev.cpt.ocp.vodacom.corp"
      - name: NEXUS_ARTIFACT_REPO
        value: "thirdparty"
      - name: NEXUS_GROUP_ID
        value: "org/thirdparty/chronograf"
      - name: NEXUS_ARTIFACT_ID
        value: "chronograf"
      - name: NEXUS_ARTIFACT_VERSION
        value: "1.6.2"
      - name: NEXUS_ARTIFACT_CLASSIFIER
        value: "1.6.2"
      - name: NEXUS_ARTIFACT_TYPE
        value: "tar.gz"
      env:
      - name: PROJECT_NAME
        value: "chronograf"
      - name: SERVICE_VERSION
        value: "1.6.2"
      - name: SERVICE_DESCRIPTION
        value: "chronograf matrix"
      - name: SERVICE_MEMORY
        value: "300M"
      - name: PORT
        value: "8888"
        protocol: TCP
      dockerfilePath: "chronograf.docker"
  output:
    to:
      kind: "ImageStreamTag"
      name: "chronograf:1.6.2"
  triggers:
  - type: "ConfigChange"
  - type: "ImageChange"
    imageChangeParams:
      automatic: true
      containerNames:
      - "chronograf"
      from:
        kind: "ImageStreamTag"
        name: "chronograf:1.6.2"
        namespace: "chronograf"
# parameters:
# - name: SOURCE_REPOSITORY_URL
#   displayName: Git Repository URL
#   description: The URL of the repository with the OpenShift templates.
#   value: https://pbdpgl1zafsrh.vodacom.corp/cicd/doctrine.git
#   required: true
# - name: SOURCE_REPOSITORY_REF
#   displayName: Git Reference
#   description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
#   value: master
#   required: true
# - name: DOCKERFILE_LOCATION
#   displayName: ruby docker file location
#   description: The location of the ruby docker files.
#   value: containers/cicd/jenkins-slaves/ruby
#   required: true